CREATE TABLE `activity` (
  `ACT_ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `ACT_DATE_CREATED` datetime DEFAULT NULL,
  `ACT_DATE_DUE` datetime DEFAULT NULL,
  `ACT_RESOLUTION_DATE` datetime DEFAULT NULL,
  `ACT_NOTE_USER_CREATE` varchar(50) DEFAULT NULL,
  `ACT_NOTE_USER_ASSIGNED` varchar(50) DEFAULT NULL,
  `ACT_USER_ASSIGNED_ID` int(11) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `PRJ_ID` int(11) DEFAULT NULL,
  `ACT_RESOLUTION_NOTES` text
 ) ;


CREATE TABLE `assignment` (
  `ASSIGN_ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `ASSIGN_NOTES` text,
  `ASSIGNEE_USER_ID` int(11) DEFAULT NULL,
  `ASSIGN_DATE` datetime DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `PRJ_ID` int(11) DEFAULT NULL
) ;




CREATE TABLE `documents` (
  `DOC_ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `DOC_TYPE` varchar(45) DEFAULT NULL,
  `DOC_URL` varchar(45) DEFAULT NULL,
  `DOC_DESC` text
); 




CREATE TABLE `note` (
  `NOTE_ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `NOTE_DATE_CREATED` datetime DEFAULT NULL,
  `NOTE_TIME` datetime DEFAULT NULL,
  `NOTE_TEXT` text,
  `USER_ID` int(11) DEFAULT NULL,
  `PRJ_ID` int(11) DEFAULT NULL
); 



CREATE TABLE `project` (
  `PRJ_ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `PRJ_NAME` varchar(100) DEFAULT NULL,
  `PRJ_DESCRIPTION` text,
  `PRJ_ACTIVE` int(4) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL
); 

CREATE TABLE `user_table` (
  `USER_ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `USER_LAST` varchar(100) DEFAULT NULL,
  `USER_LOGIN` varchar(50) DEFAULT NULL,
  `USER_PASSWORD` varchar(20) DEFAULT NULL,
  `USER_ROLE` varchar(20) DEFAULT NULL,
  `USER_FIRST` varchar(100) DEFAULT NULL,
  `USER_ACTIVE` int(4) DEFAULT NULL
); 


